name: continuous-integration

on:
  push:
    branches:
      - main
      - feature/*
      - fix/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building ..."

  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building ..."
    needs: test

  trigger-artifact-to-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: manual-trigger
        id: manual-trigger
        uses: benhamiltonpro/manual-trigger@v1
        with:
          RUN_NAME: "artifact-to-staging"
    needs: build
  
  artifact-to-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - run: echo "Promoting artifact to staging repository ..."
    needs: trigger-artifact-to-staging
  