name: continuous-integration

on:
  push:
    branches:
      - main
      - feature/*
      - fix/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building ..."

  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building ..."
    needs: test

  artifact-to-staging:
    runs-on: ubuntu-latest
    environment: staging
    if: github.ref == 'refs/heads/main'
    steps:
      - run: echo "Triggering artifact to staging repository ..."
    needs: build
    
  
  artifact-to-rc:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: release-candidate
    steps:
      - run: echo "Promoting artifact to staging repository ..."
    needs: artifact-to-staging
